'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8800
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM

Namespace PaymentCertApproval
    
    Public Class Form__frmpcapp
        Inherits B1Form
        
        Public Sub New()
            MyBase.New
            FormType = "frmpcapp"
        End Sub
        
        <B1Listener(BoEventTypes.et_FORM_LOAD, false)>  _
        Public Overridable Sub OnAfterFormLoad(ByVal pVal As ItemEvent)
            Dim ActionSuccess As Boolean = pVal.ActionSuccess
            Dim form As Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)
            'ADD YOUR ACTION CODE HERE ...
        End Sub
    End Class
End Namespace
