'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8800
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM

Namespace PaymentCertApproval
    
    Public Class PaymentCertApproval_Db
        Inherits B1Db
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
End Namespace
