'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8800
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PRExporter.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PCMS.
        '''</summary>
        Friend ReadOnly Property ApplicationName() As String
            Get
                Return ResourceManager.GetString("ApplicationName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ZHVpZnl1aTo4MzJqa2dy.
        '''</summary>
        Friend ReadOnly Property AuthKey() As String
            Get
                Return ResourceManager.GetString("AuthKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pe.history.
        '''</summary>
        Friend ReadOnly Property HistoryFile() As String
            Get
                Return ResourceManager.GetString("HistoryFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to V1.4.
        '''</summary>
        Friend ReadOnly Property HistoryVersion() As String
            Get
                Return ResourceManager.GetString("HistoryVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Require\.
        '''</summary>
        Friend ReadOnly Property RequireFolder() As String
            Get
                Return ResourceManager.GetString("RequireFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Require\QS25.rpt.
        '''</summary>
        Friend ReadOnly Property RPTFile() As String
            Get
                Return ResourceManager.GetString("RPTFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PAY800.
        '''</summary>
        Friend ReadOnly Property Server_HK_BE_DB() As String
            Get
                Return ResourceManager.GetString("Server_HK_BE_DB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to compass2008.
        '''</summary>
        Friend ReadOnly Property Server_HK_BE_DBPassword() As String
            Get
                Return ResourceManager.GetString("Server_HK_BE_DBPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sa.
        '''</summary>
        Friend ReadOnly Property Server_HK_BE_DBUserName() As String
            Get
                Return ResourceManager.GetString("Server_HK_BE_DBUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10.1.1.126.
        '''</summary>
        Friend ReadOnly Property Server_HK_BE_Server() As String
            Get
                Return ResourceManager.GetString("Server_HK_BE_Server", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PCMS800.
        '''</summary>
        Friend ReadOnly Property Server_HK_FE_DB() As String
            Get
                Return ResourceManager.GetString("Server_HK_FE_DB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to compass2009.
        '''</summary>
        Friend ReadOnly Property Server_HK_FE_DBPassword() As String
            Get
                Return ResourceManager.GetString("Server_HK_FE_DBPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sa.
        '''</summary>
        Friend ReadOnly Property Server_HK_FE_DBUserName() As String
            Get
                Return ResourceManager.GetString("Server_HK_FE_DBUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10.1.1.125.
        '''</summary>
        Friend ReadOnly Property Server_HK_FE_Server() As String
            Get
                Return ResourceManager.GetString("Server_HK_FE_Server", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MCPAY200.
        '''</summary>
        Friend ReadOnly Property Server_MS_BE_DB() As String
            Get
                Return ResourceManager.GetString("Server_MS_BE_DB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compass2008.
        '''</summary>
        Friend ReadOnly Property Server_MS_BE_DBPassword() As String
            Get
                Return ResourceManager.GetString("Server_MS_BE_DBPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sa.
        '''</summary>
        Friend ReadOnly Property Server_MS_BE_DBUserName() As String
            Get
                Return ResourceManager.GetString("Server_MS_BE_DBUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10.12.0.9.
        '''</summary>
        Friend ReadOnly Property Server_MS_BE_Server() As String
            Get
                Return ResourceManager.GetString("Server_MS_BE_Server", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MCPCMS100.
        '''</summary>
        Friend ReadOnly Property Server_MS_FE_DB() As String
            Get
                Return ResourceManager.GetString("Server_MS_FE_DB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compass2008.
        '''</summary>
        Friend ReadOnly Property Server_MS_FE_DBPassword() As String
            Get
                Return ResourceManager.GetString("Server_MS_FE_DBPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sa.
        '''</summary>
        Friend ReadOnly Property Server_MS_FE_DBUserName() As String
            Get
                Return ResourceManager.GetString("Server_MS_FE_DBUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10.12.0.8.
        '''</summary>
        Friend ReadOnly Property Server_MS_FE_Server() As String
            Get
                Return ResourceManager.GetString("Server_MS_FE_Server", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PAY800.
        '''</summary>
        Friend ReadOnly Property Server_TS_BE_DB() As String
            Get
                Return ResourceManager.GetString("Server_TS_BE_DB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to compass2008.
        '''</summary>
        Friend ReadOnly Property Server_TS_BE_DBPassword() As String
            Get
                Return ResourceManager.GetString("Server_TS_BE_DBPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sa.
        '''</summary>
        Friend ReadOnly Property Server_TS_BE_DBUserName() As String
            Get
                Return ResourceManager.GetString("Server_TS_BE_DBUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10.1.1.180.
        '''</summary>
        Friend ReadOnly Property Server_TS_BE_Server() As String
            Get
                Return ResourceManager.GetString("Server_TS_BE_Server", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PCMS800.
        '''</summary>
        Friend ReadOnly Property Server_TS_FE_DB() As String
            Get
                Return ResourceManager.GetString("Server_TS_FE_DB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to compass2009.
        '''</summary>
        Friend ReadOnly Property Server_TS_FE_DBPassword() As String
            Get
                Return ResourceManager.GetString("Server_TS_FE_DBPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sa.
        '''</summary>
        Friend ReadOnly Property Server_TS_FE_DBUserName() As String
            Get
                Return ResourceManager.GetString("Server_TS_FE_DBUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10.1.1.179.
        '''</summary>
        Friend ReadOnly Property Server_TS_FE_Server() As String
            Get
                Return ResourceManager.GetString("Server_TS_FE_Server", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MCPAY200.
        '''</summary>
        Friend ReadOnly Property Server_TW_BE_DB() As String
            Get
                Return ResourceManager.GetString("Server_TW_BE_DB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to compass2008.
        '''</summary>
        Friend ReadOnly Property Server_TW_BE_DBPassword() As String
            Get
                Return ResourceManager.GetString("Server_TW_BE_DBPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sa.
        '''</summary>
        Friend ReadOnly Property Server_TW_BE_DBUserName() As String
            Get
                Return ResourceManager.GetString("Server_TW_BE_DBUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10.12.0.2.
        '''</summary>
        Friend ReadOnly Property Server_TW_BE_Server() As String
            Get
                Return ResourceManager.GetString("Server_TW_BE_Server", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MCPCMS100.
        '''</summary>
        Friend ReadOnly Property Server_TW_FE_DB() As String
            Get
                Return ResourceManager.GetString("Server_TW_FE_DB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to compass2009.
        '''</summary>
        Friend ReadOnly Property Server_TW_FE_DBPassword() As String
            Get
                Return ResourceManager.GetString("Server_TW_FE_DBPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sa.
        '''</summary>
        Friend ReadOnly Property Server_TW_FE_DBUserName() As String
            Get
                Return ResourceManager.GetString("Server_TW_FE_DBUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10.12.0.1.
        '''</summary>
        Friend ReadOnly Property Server_TW_FE_Server() As String
            Get
                Return ResourceManager.GetString("Server_TW_FE_Server", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Require\config.xml.
        '''</summary>
        Friend ReadOnly Property SettingFile() As String
            Get
                Return ResourceManager.GetString("SettingFile", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
